name: Generate Markdown Article and Update Index and Sitemap

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Enter the topic for the article"
        required: true
        default: "GitHub Actions"
        type: string
      filename:
        description: "Enter the filename (without .md extension)"
        required: true
        default: "article"
        type: string    
      displayname:
        description: "Enter the displayname"
        required: true
        default: "001.Github Actionsについて"
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Article using Cohere API
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          # ワークフローの入力からトピックとファイル名を取得
          TOPIC="${{ github.event.inputs.topic }}"
          FILENAME="${{ github.event.inputs.filename }}.md"

          # postフォルダーが存在しない場合は作成
          mkdir -p post

          # Cohere APIを使って記事を生成
          RESPONSE=$(curl -s https://api.cohere.ai/v1/generate \
          -H "Authorization: Bearer $COHERE_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "command-xlarge-nightly",
            "prompt": "日本語で'"$TOPIC"'についての記事をMakedownで書いてください。",
            "max_tokens": 1000,
            "temperature": 0.8
          }')

          # 生成された記事を取り出す
          ARTICLE=$(echo $RESPONSE | jq -r '.generations[0].text')

          # 記事が正しく取得できているか確認
          echo "Generated Article: $ARTICLE"

          # postフォルダーに指定されたファイル名でMarkdownファイルに書き込む
          echo "$ARTICLE" > "post/$FILENAME"

      - name: Update sitemap.xml
        run: |
          # sitemap.xmlのパス
          SITEMAP_FILE="sitemap.xml"

          # 新しいURLを生成
          NEW_URL="https://hcratch3.github.io/wiki/post/${{ github.event.inputs.filename }}.md"

          # sitemap.xmlが存在するか確認し、なければ作成
          if [ ! -f "$SITEMAP_FILE" ]; then
            echo '<?xml version="1.0" encoding="UTF-8"?>' > $SITEMAP_FILE
            echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> $SITEMAP_FILE
            echo '</urlset>' >> $SITEMAP_FILE
          fi

          # 新しいURLをsitemap.xmlに追加
          sed -i '$i <url><loc>'$NEW_URL'</loc></url>' $SITEMAP_FILE

      - name: Update index.md with new article
        run: |
          # index.mdファイルのパス
          INDEX_FILE="index.md"

          # 新しい記事のリンクを作成
          NEW_ENTRY="- [${{ github.event.inputs.displayname }}](post/${{ github.event.inputs.filename }}.md)"

          # 総目次セクションに新しい記事を追加
          sed -i '/## 総目次/a '"$NEW_ENTRY" "$INDEX_FILE"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "your-username"
          git add post/"$FILENAME" sitemap.xml index.md
          git commit -m "Generate article about $TOPIC, update sitemap.xml and index.md"
          git push
