name: Generate Markdown Article with Cohere API

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Enter the topic for the article"
        required: true
        default: "GitHub Actions"
        type: string
      filename:
        description: "Enter the filename (without .md extension)"
        required: true
        default: "article"
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Article using Cohere API
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          # ワークフローの入力からトピックとファイル名を取得
          TOPIC="${{ github.event.inputs.topic }}"
          FILENAME="${{ github.event.inputs.filename }}.md"

          # postフォルダーが存在しない場合は作成
          mkdir -p post

          # Cohere APIを使って記事を生成
          RESPONSE=$(curl -s https://api.cohere.ai/v1/generate \
          -H "Authorization: Bearer $COHERE_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "command-xlarge-nightly",
            "prompt": "日本語で"$TOPIC"についての詳細なマークダウン記事を書いてください。",
            "max_tokens": 500,
            "temperature": 0.8
          }')

          # 生成された記事を取り出す
          ARTICLE=$(echo $RESPONSE | jq -r '.generations[0].text')

          # 記事が正しく取得できているか確認
          echo "Generated Article: $ARTICLE"

          # postフォルダーに指定されたファイル名でMarkdownファイルに書き込む
          echo "$ARTICLE" > "post/$FILENAME"

      - name: Commit and Push Article
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "your-username"
          git add post/"$FILENAME"
          git commit -m "Generate article about $TOPIC with filename $FILENAME"
          git push
