name: Generate Markdown Article

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Enter the topic for the article"
        required: true
        default: "GitHub Actions"
        type: string
      filename:
        description: "Enter the filename (without .md extension)"
        required: true
        default: "article"
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # ワークフローの入力からトピックとファイル名を取得
          TOPIC="${{ github.event.inputs.topic }}"
          FILENAME="${{ github.event.inputs.filename }}.md"

          # postフォルダーが存在しない場合は作成
          mkdir -p post

          # OpenAI APIを使って記事を生成
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-3.5-turbo",
            "messages": [{"role": "user", "content": "Write a markdown article about '"$TOPIC"'."}],
            "max_tokens": 500
          }')

          # 生成された記事を取り出す
          ARTICLE=$(echo $RESPONSE | jq -r '.choices[0].message.content')

          # postフォルダーに指定されたファイル名でMarkdownファイルに書き込む
          echo "$ARTICLE" > "post/$FILENAME"

      - name: Commit and Push Article
        run: |
          git config --local user.email "hcratch@outlook.com"
          git config --local user.name "hcratch3"
          git add post/"$FILENAME"
          git commit -m "Generate article about $TOPIC with filename $FILENAME"
          git push
