name: Dynamic Gemini AI Content Generation

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Enter the prompt for Gemini AI'
        required: true
        default: 'Write about the importance of AI in software development.'

jobs:
  generate-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Generate text using Gemini AI
      run: |
        echo '{
          "prompt": "${{ github.event.inputs.prompt }}",
          "max_tokens": 300
        }' > prompt.json
        python generate_gemini_content.py

    - name: Move generated content to post folder
      run: |
        mkdir -p post
        mv generated_content.txt post/$(date +%Y-%m-%d)-generated-content.txt

    - name: Commit generated content
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add post/
        git commit -m "Add content generated by Gemini AI"
        git push
